version: "3.10"
services:
  worker:
    build: .
    environment:
       API_ID: $API_ID
       API_HASH: $API_HASH
       SESSION: $SESSION
       BOT_TOKEN: $BOT_TOKEN
       CACHE_TIME: $CACHE_TIME
       USE_CAPTION_FILTER: $USE_CAPTION_FILTER
       PICS: $PICS
       ADMINS: $ADMINS
       CHANNELS: $CHANNELS
       AUTH_USERS: $AUTH_USERS
       AUTH_CHANNEL: $AUTH_CHANNEL
       AUTH_GROUPS: $AUTH_GROUPS
       DATABASE_URI: $DATABASE_URI
       DATABASE_NAME: $DATABASE_NAME
       COLLECTION_NAME: $COLLECTION_NAME
       LOG_CHANNEL: $LOG_CHANNEL
       SUPPORT_CHAT: $SUPPORT_CHAT
       P_TTI_SHOW_OFF: $P_TTI_SHOW_OFF
       IMDB: $IMDB
       SINGLE_BUTTON: $SINGLE_BUTTON
       CUSTOM_FILE_CAPTION: $CUSTOM_FILE_CAPTION
       BATCH_FILE_CAPTION: $BATCH_FILE_CAPTION
       IMDB_TEMPLATE: $IMDB_TEMPLATE
       LONG_IMDB_DESCRIPTION: $LONG_IMDB_DESCRIPTION
       SPELL_CHECK_REPLY: $SPELL_CHECK_REPLY
       MAX_LIST_ELM: $MAX_LIST_ELM
       INDEX_REQ_CHANNEL: $INDEX_REQ_CHANNEL
       FILE_STORE_CHANNEL: $FILE_STORE_CHANNEL
       MELCOW_NEW_USERS: $MELCOW_NEW_USERS
       PROTECT_CONTENT: $PROTECT_CONTENT
       PUBLIC_FILE_STORE: $PUBLIC_FILE_STORE
